test build

diff --git a/cloudbuild-dev.yaml b/cloudbuild-dev.yaml
--- a/cloudbuild-dev.yaml
+++ b/cloudbuild-dev.yaml
@@ -7,6 +7,27 @@ steps:
   - name: "gcr.io/cloud-builders/docker"
     args: ["push", "europe-west2-docker.pkg.dev/${PROJECT_ID}/docker-images/cir-converter-service:$SHORT_SHA"]
 
+  - name: "gcr.io/cloud-builders/gcloud"
+    id: "Show image vulnerabilities"
+    entrypoint: bash
+    args:
+      - "-c"
+      - |
+        gcloud artifacts vulnerabilities list europe-west2-docker.pkg.dev/${PROJECT_ID}/sds/sds:latest \
+          --format=json > /workspace/vulnerability_report
+
+  - name: "gcr.io/cloud-builders/gcloud"
+    id: "Check for critical vulnerabilities"
+    entrypoint: bash
+    args:
+      - "-c"
+      - |
+        apt-get -y update && apt-get install -y jq
+        if jq -e '.[] | select( .vulnerability.effectiveSeverity == "CRITICAL")' /workspace/vulnerability_report > /dev/null; then
+          echo "Error: Critical vulnerability found with image"
+          exit 1
+        fi
+
   # Deploy the container to Google Cloud Run
   - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
     id: "Run container"
