test build

diff --git a/cloudbuild-dev.yaml b/cloudbuild-dev.yaml
--- a/cloudbuild-dev.yaml
+++ b/cloudbuild-dev.yaml
@@ -13,13 +13,8 @@ steps:
     args:
       - "-c"
       - |
-        if [ ${PROJECT_ID} == "ons-cir-mig-dev" || ${PROJECT_ID} == "ons-cir-mig-sandbox"]
-        then
-          gcloud artifacts vulnerabilities list europe-west2-docker.pkg.dev/${PROJECT_ID}/docker-images/cir-converter-service:$SHORT_SHA \
-            --format=json > /workspace/vulnerability_report
-        else
-          echo "Step not run for ${PROJECT_ID}"
-        fi
+        gcloud artifacts vulnerabilities list europe-west2-docker.pkg.dev/${PROJECT_ID}/docker-images/cir-converter-service:$SHORT_SHA \
+          --format=json > /workspace/vulnerability_report
 
   - name: "gcr.io/cloud-builders/gcloud"
     id: "Check for critical vulnerabilities"
@@ -27,15 +22,10 @@ steps:
     args:
       - "-c"
       - |
-        if [ ${PROJECT_ID} == "ons-cir-mig-dev" || ${PROJECT_ID} == "ons-cir-mig-sandbox" ]
-        then
-          apt-get -y update && apt-get install -y jq
-          if jq -e '.[] | select( .vulnerability.effectiveSeverity == "CRITICAL")' /workspace/vulnerability_report > /dev/null; then
-            echo "Error: Critical vulnerability found with image"
-            exit 1
-          fi
-        else
-          echo "Step not run for ${PROJECT_ID}"
+        apt-get -y update && apt-get install -y jq
+        if jq -e '.[] | select( .vulnerability.effectiveSeverity == "CRITICAL")' /workspace/vulnerability_report > /dev/null; then
+          echo "Error: Critical vulnerability found with image"
+          exit 1
         fi
 
   # Deploy the container to Google Cloud Run
